name: Deploy Frontend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ vars.SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Install dependencies and build
        run: |
          cd frontend/agro_predict
          npm install
          npm run build

      - name: Deploy to GCS
        run: |
          gsutil -m rsync -r frontend/agro_predict/dist gs://${{ vars.GCP_BUCKET_NAME }}

      - name: Make all bucket files public
        run: |
          gsutil -m acl ch -r -u AllUsers:R gs://${{ vars.GCP_BUCKET_NAME }}
