name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ vars.SERVICE_ACCOUNT }}

      # Step 3: Setup gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      # Step 4: Build Docker image for frontend
      - name: Build frontend Docker image
        run: |
          cd frontend/agro_predict
          gcloud builds submit . --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/frontend

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/frontend \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
