name: Deploy Frontend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to GCP using SERVICE_ACCOUNT (as repo variable)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ vars.SERVICE_ACCOUNT }}

      # Step 3: Setup gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      # (Optional) Step 4: Build frontend
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 5: Deploy build output to GCS bucket
      - name: Deploy to GCS
        run: |
          gsutil -m rsync -r ./dist gs://${{ vars.GCP_BUCKET_NAME }}
